# Generated by Django 5.2.13 on 2026-04-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'citizens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'conductors',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pass_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('pass_type', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'system_admins',
            },
        ),
    ]
